python_binary(
  sources = ['client.py'],
#  entry_point='example.client',
  dependencies=[
      '3rdparty/python:grpcio',

      'src/python/utils',

      'src/proto/example/book',
      'src/proto/example/author',
  ]
)