# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  sources=['python_grpcio_library.py'],
  dependencies = [
    '3rdparty/python:future',
    'src/python/pants/backend/python/targets',
  ],
)